export const CHECK = {
  CHECK: 'CHECK/LOADING',
  CHECK_SUCCESS: 'CHECK/CHECK_SUCCESS',
  CHECK_FAIL: 'CHECK/CHECK_FAIL',
};

export const GET_IS_CHECK = {
  GET_IS_CHECK: 'GET_IS_CHECK/LOADING',
  GET_IS_CHECK_SUCCESS: 'GET_IS_CHECK/GET_IS_CHECK_SUCCESS',
  GET_IS_CHECK_FAIL: 'GET_IS_CHECK/GET_IS_CHECK_FAIL',
};
