export const VERIFY = 'USER/VERIFY';

export const LOGIN = {
  LOADING: 'USER/LOADING',
  LOGIN_SUCCESS: 'USER/LOGIN_SUCCESS',
  LOGIN_FAIL: 'USER/LOGIN_FAIL',
  LOGOUT: 'USER/LOG_OUT',
  VERIFY: 'USER/VERIFY',
};
