export const GET_TIME_SHEETS = {
  GET_TIME_SHEETS: 'GET_TIME_SHEETS/LOADING',
  GET_TIME_SHEETS_SUCCESS: 'GET_TIME_SHEETS/GET_TIME_SHEETS_SUCCESS',
  GET_TIME_SHEETS_FAIL: 'GET_TIME_SHEETS/GET_TIME_SHEETS_FAIL',
  RESET: 'GET_TIME_SHEETS/RESET',
};
export const GET_TIME_SHEETS_ADMIN = {
  GET_TIME_SHEETS_ADMIN: 'ADMIN/LOADING',
  GET_TIME_SHEETS_ADMIN_SUCCESS: 'ADMIN/GET_TIME_SHEETS_ADMIN_SUCCESS',
  GET_TIME_SHEETS_ADMIN_FAIL: 'ADMIN/GET_TIME_SHEETS_ADMIN_FAIL',
};
export const EVENT = {
  RESET: 'TIME_SHEETS/RESET',
};
